controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_create_qa:
    path: /qa
    controller: App\Controller\QaController::create
    methods: ['POST']
